# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-24 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190824_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaner',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='cleaner',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
