# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-24 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time',
        ),
    ]
